### PR TITLE
Translate TestCanceled to fireAssumptionFailed

### PR DESCRIPTION
**Pull request by retronym**

### CODE REVIEW

**Comment by artimasites** [comment]
@cla-bot[bot] check

**Comment by cheeseng** [comment]
@retronym Thanks for the PR!  The changes looks good!  I'll port this over to scalatest+junit5 as well.

**Comment by lrytz** [comment]
Bump 🛎️

**Review by bvenners — APPROVED** [review]

**Comment by tech-jun-jones** [comment]
retronym:feature/assumption-failure

**Comment by tech-jun-jones** [comment]
class IterablePublisherTest(env: TestEnvironment, publisherShutdownTimeout: Long)
  extends PublisherVerification[Int](env, publisherShutdownTimeout)
  with TestNGSuiteLike {

  def this() {
    this(new TestEnvironment(500), 1000)
  }

  def createPublisher(elements: Long): Publisher[Int] = ???

  // example error state publisher implementation
  override def createFailedPublisher(): Publisher[Int] =
    new Publisher[Int] {
      override def subscribe(s: Subscriber[Int]): Unit =
        s.onError(new Exception("Unable to serve subscribers right now!"))
    }

}

**Pull request merged**
